os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

before_script:
  - cd lib
  - mv tmdb_config.dart.sample tmdb_config.dart
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov

script:
  - ./flutter/bin/flutter test --coverage

after_success:
  - coveralls-lcov coverage/lcov.info

cache:
  directories:
    - $HOME/.pub-cache