default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play internal testing"
  lane :internal do
    upload_to_play_store(apk: "../build/app/outputs/apk/release/app-release.apk", track: "internal")
  end
end
