name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ironman <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  core:
    path: ../core
  angular: ^5.3.0
#  angular_components: ^0.13.0
  angular_router: ^2.0.0-alpha+19
  key_value_store_web: ^1.0.0
  pwa: ^0.1.11

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: '>=1.3.0 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  build_daemon: ^1.0.0
  build_test: ^0.10.3
  sass_builder: ^2.1.1
  test: ^1.3.0
